### ISSUE TITLE
Error FAQ extension

### ISSUE THREAD

**Issue by LEFTSkateshop** [abdev/magento-FAQ#2]
The module works great or at least i thought it works great but my log keeps giving this error.

2011-03-11T11:30:12+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Ongeldig bloktype: Mage_Adminhtml_Block_FaqArticles_Edit_Form' in /home/users/leftnftp/left.nl/app/Mage.php:550
Stack trace:
#0 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Model/Layout.php(469): Mage::throwException('Ongeldig blokty...')
#1 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Model/Layout.php(411): Mage_Core_Model_Layout->_getBlockInstance('adminhtml/faqAr...', Array)
#2 /home/users/leftnftp/left.nl/app/code/core/Mage/Adminhtml/Block/Widget/Form/Container.php(82): Mage_Core_Model_Layout->createBlock('adminhtml/faqAr...')
#3 /home/users/leftnftp/left.nl/app/code/community/PWS/FAQ/Block/Adminhtml/Faq/Articles/Edit.php(55): Mage_Adminhtml_Block_Widget_Form_Container->_prepareLayout()
#4 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Block/Abstract.php(223): PWS_FAQ_Block_Adminhtml_Faq_Articles_Edit->_prepareLayout()
#5 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Model/Layout.php(430): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#6 /home/users/leftnftp/left.nl/app/code/community/PWS/FAQ/controllers/Adminhtml/FaqArticlesController.php(36): Mage_Core_Model_Layout->createBlock('pws_faq/adminht...')
#7 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Controller/Varien/Action.php(418): PWS_FAQ_Adminhtml_FaqArticlesController->editAction()
#8 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(253): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/users/leftnftp/left.nl/app/code/core/Mage/Core/Model/App.php(304): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/users/leftnftp/left.nl/app/Mage.php(596): Mage_Core_Model_App->run(Array)
#12 /home/users/leftnftp/left.nl/index.php(81):

I get the feeling it has something to do with my WYSIWYG editor. It doen's work with this extension dispite of the button.

Thanks for the support. 

John

www.LEFT.nl

**Comment by pauldpauld** [comment]
Hi John,

did you ever get this fixed? I am using this on 4.1.1.1 and my wysiwyg also is not working. Any thoughts appreciated!
